version: '3'
services:

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - ./nginx/:/src/nginx/
      - static_volume:/env_root/static_root/
      - media_volume:/env_root/media_root/

  web:
    build: .
    restart: always
    command: gunicorn telkomcdm.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - .:/src/
      - static_volume:/env_root/static_root/
      - media_volume:/env_root/media_root/
    env_file:
      - ./.env

  db:
    image: postgres:12.0-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.db.env

volumes:
  postgres_data:
  static_volume:
  media_volume:
